import { Command } from 'commander';
import { findProjectRoot, resolveSpecforgePath } from '../utils/path-utils.js';
import { logger } from '../utils/logger.js';
import { loadChangeMetadata } from '../core/change.js';
import { ArtifactGraph } from '../core/artifact-graph/graph.js';
import { detectArtifactStates } from '../core/artifact-graph/state.js';
import { loadProjectConfig } from '../core/project-config.js';
import { resolveSchema } from '../core/artifact-graph/resolver.js';
import {
  createGitIntegration,
  conventionalCommit,
  changeBranchName,
} from '../core/git-integration.js';
import { deepValidate } from '../core/smart-validate.js';
import { intro, outro, spinner as clackSpinner } from '@clack/prompts';
import { execSync } from 'node:child_process';
import { CHANGES_DIR } from '../utils/constants.js';

export const publishCommand = new Command('publish')
  .description(
    'Verify completion, commit with conventional commits, and open a PR via GitHub CLI',
  )
  .argument('<change>', 'Name of the change to publish')
  .action(async (changeName: string) => {
    const s = clackSpinner();
    try {
      intro(`SpecForge GitOps - Publishing ${changeName}`);
      const projectRoot = await findProjectRoot();
      if (!projectRoot) {
        logger.error('Not inside a SpecForge project.');
        process.exitCode = 1;
        return;
      }

      const changeDir = resolveSpecforgePath(projectRoot, CHANGES_DIR, changeName);
      const metadata = await loadChangeMetadata(changeDir);

      if (!metadata) {
        logger.error(`Change "${changeName}" not found.`);
        process.exitCode = 1;
        return;
      }

      const config = await loadProjectConfig(projectRoot);
      const schemaName = metadata.schema ?? config.schema;
      const schema = await resolveSchema(schemaName, projectRoot);
      const graph = new ArtifactGraph(schema);

      s.start('Validating artifact completion (Deep validation)...');
      await detectArtifactStates(graph, changeDir);
      const validationReport = await deepValidate(graph, changeDir);

      if (
        validationReport.score < 100 ||
        validationReport.issues.some((i) => i.level === 'error')
      ) {
        s.stop('Validation failed');
        logger.error('Cannot publish because artifacts are not 100% complete.');
        for (const issue of validationReport.issues) {
          logger.error(`[${issue.level}] ${issue.message}`);
        }
        process.exitCode = 1;
        return;
      }
      s.stop('Validation complete (100%)');

      s.start('Creating conventional commit and pushing branch...');
      const git = await createGitIntegration(projectRoot);
      if (!git) {
        s.stop('Git initialization failed');
        logger.error('Git integration failed or repository not found.');
        process.exitCode = 1;
        return;
      }

      const branchName = changeBranchName(changeName);

      try {
        await git.createBranch(branchName);
      } catch {
        // Assume branch might exist
      }

      const asanaTag = metadata.tags?.find((t) => t.startsWith('asana-'));
      const asanaRef = asanaTag ? ` (Asana #${asanaTag.replace('asana-', '')})` : '';

      const msg = conventionalCommit(
        'feat',
        changeName,
        `Complete workflow specifications for ${changeName}${asanaRef}`,
      );

      await git.commit(msg);

      // Push branch
      await git.push('origin', branchName, ['-u']);
      s.stop('Git pushed successfully');

      s.start('Opening Pull Request via GitHub CLI...');
      try {
        const prTitle = `feat: ${changeName}${asanaRef}`;
        const prBody = `This PR was automatically generated by SpecForge GitOps.\n\nAll specifications for \`${changeName}\` have been verified at 100%.`;
        execSync(`gh pr create --title "${prTitle}" --body "${prBody}"`, {
          stdio: 'inherit',
        });
        s.stop('Pull Request opened successfully');
      } catch (err) {
        s.stop('Failed to open Pull Request via GitHub CLI');
        logger.warn('Make sure GitHub CLI (gh) is installed and authenticated.');
        logger.warn(String(err));
      }

      outro('Zero-Touch Publication Complete!');
    } catch (error) {
      s.stop('Publish failed');
      logger.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    }
  });
