import { join } from 'node:path';
import { writeTextFile, pathExists } from '../utils/file-system.js';
import { loadProjectConfig } from './project-config.js';
import { resolveSchema } from './artifact-graph/resolver.js';
import { ArtifactGraph } from './artifact-graph/graph.js';
import { detectArtifactStates } from './artifact-graph/state.js';
import { CHANGES_DIR } from '../utils/constants.js';
import { resolveSpecforgePath } from '../utils/path-utils.js';
import { readdir } from 'node:fs/promises';

export interface AgentContextOptions {
  /** Name of a specific change to include status for */
  changeName?: string;
  /** Output format(s) to generate. Defaults to both `['cursorrules', 'clinerules']` when not provided. */
  formats?: Array<'cursorrules' | 'clinerules'>;
}

export interface AgentContextResult {
  /** Files written by this operation */
  filesWritten: string[];
  /** The generated rules content */
  content: string;
}

/**
 * Generate agent-context rules files (`.cursorrules` / `.clinerules`) that teach
 * an IDE AI agent (Cursor, Cline, Copilot, etc.) how to interact with SpecForge
 * through "slash commands" and how to perform self-healing validation.
 */
export async function generateAgentContext(
  projectRoot: string,
  options: AgentContextOptions = {},
): Promise<AgentContextResult> {
  const formats = options.formats ?? ['cursorrules', 'clinerules'];

  const config = await loadProjectConfig(projectRoot);
  const schema = await resolveSchema(config.schema, projectRoot);

  // Collect status snapshot for the requested (or most recent active) change
  let statusSnapshot = '';
  try {
    statusSnapshot = await buildStatusSnapshot(
      projectRoot,
      config.schema,
      options.changeName,
    );
  } catch {
    // Non-fatal — status snapshot is best-effort
  }

  const content = buildRulesContent({
    schema: schema.name,
    schemaDescription: schema.description,
    artifactIds: schema.artifacts.map((a) => a.id),
    projectContext: config.context,
    statusSnapshot,
  });

  const filesWritten: string[] = [];

  for (const format of formats) {
    const fileName = format === 'cursorrules' ? '.cursorrules' : '.clinerules';
    const filePath = join(projectRoot, fileName);
    await writeTextFile(filePath, content);
    filesWritten.push(filePath);
  }

  return { filesWritten, content };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

interface RulesContentParams {
  schema: string;
  schemaDescription: string;
  artifactIds: string[];
  projectContext?: string;
  statusSnapshot: string;
}

function buildRulesContent(params: RulesContentParams): string {
  const { schema, schemaDescription, artifactIds, projectContext, statusSnapshot } =
    params;
  const artifactList = artifactIds.map((id) => `  - \`${id}\``).join('\n');

  return `# SpecForge Agent Context
<!-- Auto-generated by \`specforge context\`. Re-run to refresh. -->

## About SpecForge

SpecForge is a Spec-Driven Development (SDD) framework that models software development as a
Directed Acyclic Graph (DAG) of artifacts. Each artifact (e.g. proposal, specs, design) must be
completed before dependent artifacts are started — but the **Fluid DAG** mode allows out-of-order
editing and tracks consistency automatically.

## Active Workflow Schema: \`${schema}\`

${schemaDescription}

### Artifacts in this schema
${artifactList}

${projectContext ? `## Project Context\n\n${projectContext}\n` : ''}
${statusSnapshot ? `## Current Project Status\n\n${statusSnapshot}\n` : ''}
## Slash Commands

Use these virtual commands in this chat to interact with SpecForge:

### \`/forge:propose [change-name]\`
Create or update the **proposal** artifact for a change.
- Run \`specforge status <change-name>\` to check the current state.
- Edit or create \`.specforge/changes/<change-name>/proposal.md\` with the feature proposal.
- Follow the structure: Background, Goals, Non-Goals, Proposed Solution, Success Criteria.

### \`/forge:apply [change-name]\`
Apply pending specifications — generate or update dependent artifacts after the proposal is ready.
- Run \`specforge instructions <change-name> <artifact-id>\` for each pending artifact to get the AI prompt.
- Create/update the artifact files as instructed.

### \`/forge:validate [change-name]\`
Validate specifications and trigger **self-healing** if the score is below 90.
1. Run: \`specforge validate <change-name> --deep --json\`
2. Parse the JSON output (fields: \`score\`, \`valid\`, \`issues\`, \`selfHealingInstructions\`).
3. If \`score < 90\`, follow each item in \`selfHealingInstructions\` to fix documentation or align code with specs before marking the task done.
4. Re-run validation until \`score >= 90\`.

### \`/forge:status [change-name]\`
Show the current DAG status of all artifacts for a change.
- Run: \`specforge status <change-name> --json\`
- Artifacts with status \`diverged\` were created out of order — they are valid but their dependencies need attention.
- Artifacts with status \`needs-sync\` have outdated content relative to updated dependencies.

### \`/forge:archive [change-name]\`
Archive a completed change.
- Ensure \`/forge:validate\` passes (score ≥ 90) first.
- Run: \`specforge archive <change-name>\`

## Self-Healing Workflow

When \`specforge validate --deep --json\` returns a score below 90:

\`\`\`
score < 90  →  read selfHealingInstructions[]
            →  for each instruction: apply fix (update docs or align code)
            →  re-run specforge validate --deep --json
            →  repeat until score >= 90
\`\`\`

## Key SpecForge CLI Reference

| Command | Purpose |
|---------|---------|
| \`specforge status <change> --json\` | Machine-readable artifact status |
| \`specforge validate <change> --deep --json\` | Score + self-healing hints (JSON) |
| \`specforge instructions <change> <artifact>\` | AI prompt for generating an artifact |
| \`specforge new-change <name>\` | Create a new change |
| \`specforge archive <change>\` | Archive a completed change |
| \`specforge context\` | Refresh this rules file |

## DAG Consistency Model (Fluid DAG)

| Status | Meaning | Action |
|--------|---------|--------|
| \`pending\` | Waiting for dependencies | Complete dependencies first |
| \`ready\` | All dependencies done, not started | Start generating this artifact |
| \`in-progress\` | Being worked on | Continue |
| \`completed\` | Done and up to date | No action |
| \`diverged\` | Files exist but dependencies incomplete | Allowed — update dependencies when ready |
| \`needs-sync\` | Completed, but dependencies were updated later | Re-align content with updated dependencies |
`;
}

async function buildStatusSnapshot(
  projectRoot: string,
  schemaName: string,
  changeName?: string,
): Promise<string> {
  const changesDir = resolveSpecforgePath(projectRoot, CHANGES_DIR);
  if (!(await pathExists(changesDir))) return '';

  let names: string[] = [];

  if (changeName) {
    names = [changeName];
  } else {
    const entries = await readdir(changesDir, { withFileTypes: true });
    names = entries
      .filter((e) => e.isDirectory() && e.name !== 'archive')
      .map((e) => e.name)
      .slice(0, 3); // Show up to 3 changes
  }

  if (names.length === 0) return '';

  const lines: string[] = [];

  for (const name of names) {
    const changeDir = join(changesDir, name);
    if (!(await pathExists(changeDir))) continue;

    try {
      const schema = await resolveSchema(schemaName, projectRoot);
      const graph = new ArtifactGraph(schema);
      await detectArtifactStates(graph, changeDir);
      const summary = graph.getSummary();

      lines.push(`**Change: ${name}**`);
      lines.push(`- completed: ${summary.completed.join(', ') || 'none'}`);
      if (summary.diverged.length > 0) {
        lines.push(`- diverged (out-of-order): ${summary.diverged.join(', ')}`);
      }
      if (summary['needs-sync'].length > 0) {
        lines.push(`- needs-sync: ${summary['needs-sync'].join(', ')}`);
      }
      if (summary.ready.length > 0) {
        lines.push(`- ready to work on: ${summary.ready.join(', ')}`);
      }
      lines.push('');
    } catch {
      // Ignore errors for individual changes
    }
  }

  return lines.join('\n');
}
